version: '3.6'
services:
  ## MySQL
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    networks:
      - default # port 3306
    volumes:
      - "./mysql/init/init.sql:/data/application/init.sql"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ## PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8082:80

  ## WebServer (PHP Apache)
  www:
    build: './src'
    image: php:8.1-apache
    depends_on:
      - db
    ports: 
      - "8080:80"
    volumes:
      - ./src/www:/var/www/html/
    environment:
      MYSQL_DB: example
      MYSQL_USER: user
      MYSQL_PASSWD: password